import pandas as pd
import numpy as np
import pytest
import config

from pipeline.preprocess import (
    load_data,
    remove_duplicates,
    fix_data_types,
    split_test_train,
    fit_encoder,
    apply_encoder,
    fit_imputer,
    apply_imputer,
    fit_standard_scaler,
    apply_standard_scaler,
    fit_variance_threshold,
    apply_variance_threshold,
    find_correlated_features,
    run_preprocessing
)

# Test load_data
def test_load_data(tmp_path):

    input_file = tmp_path / "test_qc.tsv"

    df = pd.DataFrame({
        "sample_name": ["A", "B"],
        "picard_fold80": ["1.5", "2.0"],
        "cancer_type": ["ST", "haem"],
        "sequencer": ["novaseqx", "novaseq6000"]
    })

    df.to_csv(input_file, sep="\t", index=False)

    result = load_data(input_file)

    assert isinstance(result, pd.DataFrame)
    assert result.shape == (2, 4)
    assert list(result.columns) == list(df.columns)

# Test remove_duplicates 
def test_remove_duplicates():

    df = pd.DataFrame({
        "sample_name": ["A", "B", "B", "C", "D"],
        "value": [1, 2, 2, 3, 4]
    })

    result = remove_duplicates(df)

    assert len(result) == 4
    assert result["sample_name"].tolist() == ["A", "B", "C", "D"]

# Test fix_data_types
def test_fix_data_types():

    df = pd.DataFrame({
        "picard_fold80": ["1.794", "?", "2.000"],
        "sequencer": ["novaseqx", "novaseqx", "novaseq6000"],
        "cancer_type": ["solid_tumour", "haem_v2", "solid_tumour"]
    })

    result = fix_data_types(df)

    assert pd.api.types.is_float_dtype(
        result["picard_fold80"]
    )
    assert pd.isna(result.loc[1, "picard_fold80"])
    assert result.loc[0, "picard_fold80"] == pytest.approx(1.794)
    assert result.loc[0, "assay"] == "novaseqx_solid_tumour"
    assert result.loc[2, "assay"] == "novaseq6000_solid_tumour"

# create the test
def create_test_qc_data(n_per_group=5):

    rows = []
    sample_number = 1

    # Create enough samples for stratified train/test splitting
    for sequencer in ["novaseqx", "novaseq6000"]:
        for cancer_type in ["solid_tumour", "haem"]:

            for _ in range(n_per_group):

                row = {
                    "sample_name": f"sample{sample_number}",
                    "sequencer": sequencer,
                    "cancer_type": cancer_type,
                    "fastqc_basic_status": (
                        "pass|pass"
                        if sample_number % 2 == 0
                        else "pass|pass|pass|pass"
                    )
                }

                rows.append(row)
                sample_number += 1

    df = pd.DataFrame(rows)

    # Add all numerical model features required by the pipeline
    for i, feature in enumerate(config.MODEL_FEATURES):

        # These two columns are generated by OneHotEncoder,
        # so they should NOT be present in the raw input.
        if feature.startswith("fastqc_basic_status_"):
            continue

        # Add simple numeric test values
        df[feature] = np.arange(1, len(df) + 1, dtype=float) + i

    return df

# Test the train_test_split
def test_split_test_train():

    df = create_test_qc_data()

    train, test = split_test_train(df)

    assert len(train) == 16
    assert len(test) == 4
    assert set(train.index).isdisjoint(test.index)


# Test the encoder functions 
def test_fit_encoder():

    df = pd.DataFrame({
        "fastqc_basic_status": [
            "pass|pass",
            "pass|pass|pass|pass",
            "pass|pass"
        ]
    })

    encoder = fit_encoder(df)

    assert len(encoder.categories_[0]) == 2

def test_apply_encoder():

    df = pd.DataFrame({
        "fastqc_basic_status": [
            "pass|pass",
            "pass|pass|pass|pass"
        ]
    })

    encoder = fit_encoder(df)

    result = apply_encoder(df, encoder)

    assert "fastqc_basic_status_pass|pass" in result.columns

    assert (
        "fastqc_basic_status_pass|pass|pass|pass"
        in result.columns
    )

    assert len(result) == 2
    assert result.loc[0, "fastqc_basic_status_pass|pass"] == 1
    assert result.loc[1, "fastqc_basic_status_pass|pass|pass|pass"] == 1

# Test the imputer

def create_test_feature_data(n=20):

    data = {}

    for i, feature in enumerate(config.MODEL_FEATURES):
        data[feature] = [
            float(j + i + 1)
            for j in range(n)
        ]

    return pd.DataFrame(data)

def test_imputer():

    train = create_test_feature_data()

    imputer = fit_imputer(train)

    result = apply_imputer(train, imputer)

    assert not result.isna().any().any()
    assert result.loc[1, "feature_b"] == 20.0

def test_imputer():

    train = create_test_feature_data()

    train.loc[0, "picard_fold80"] = np.nan

    imputer = fit_imputer(train)

    result = apply_imputer(train, imputer)

    assert not result.isna().any().any()

def test_imputer():

    train = create_test_feature_data()

    train.loc[0, "picard_fold80"] = np.nan

    expected_median = train["picard_fold80"].median()

    imputer = fit_imputer(train)
    result = apply_imputer(train, imputer)

    assert result.loc[0, "picard_fold80"] == expected_median


# Test the standardScaler
def test_standard_scaler():

    train = create_test_feature_data()

    scaler = fit_standard_scaler(train)

    result = apply_standard_scaler(train, scaler)

    assert result.shape == train.shape

    for column in result.columns:
        assert result[column].mean() == pytest.approx(0.0)
        assert result[column].std(ddof=0) == pytest.approx(1.0)


def test_standard_scaler():

    train = create_test_feature_data()

    scaler = fit_standard_scaler(train)

    result = apply_standard_scaler(train, scaler)

    assert result.shape == train.shape

    for column in result.columns:
        assert result[column].mean() == pytest.approx(0.0)
        assert result[column].std(ddof=0) == pytest.approx(1.0)

def test_scaler_is_fitted_on_training_data_only():

    train = create_test_feature_data(n=20)

    test = create_test_feature_data(n=5) * 100

    scaler = fit_standard_scaler(train)

    result = apply_standard_scaler(test, scaler)

    # Test values should be transformed using
    # the mean/std learned from training.
    assert result.iloc[0, 0] > 0

# Test the variance threshold
def test_variance_threshold():

    df = pd.DataFrame({
        "useful_feature": [1, 2, 3, 4, 5],
        "constant_feature": [1, 1, 1, 1, 1]
    })

    vt = fit_variance_threshold(
        df,
        threshold=0.0
    )

    result = apply_variance_threshold(df, vt)

    assert "useful_feature" in result.columns
    assert "constant_feature" not in result.columns

# Test the correlation function 
def test_find_correlated_features():

    df = pd.DataFrame({
        "feature_a": [1, 2, 3, 4, 5],
        "feature_b": [2, 4, 6, 8, 10],
        "feature_c": [5, 1, 4, 2, 3]
    })

    result = find_correlated_features(
        df,
        threshold=0.95
    )

    assert len(result) == 1

    assert result.iloc[0]["feature_1"] == "feature_a"
    assert result.iloc[0]["feature_2"] == "feature_b"
    assert result.iloc[0]["correlation"] == pytest.approx(1.0)


def test_find_correlated_features_threshold():

    df = pd.DataFrame({
        "a": [1, 2, 3, 4, 5],
        "b": [2, 4, 6, 8, 10]
    })

    result = find_correlated_features(
        df,
        threshold=1.1
    )

    assert result.empty

# Test the preprocessing script 
def test_run_preprocessing(tmp_path):

    input_file = tmp_path / "input.tsv"
    output_dir = tmp_path / "output"

    # Create realistic test data
    df = create_test_qc_data()

    # Write test data to a temporary TSV
    df.to_csv(
        input_file,
        sep="\t",
        index=False
    )

    # Run the complete preprocessing pipeline
    X_train, X_test = run_preprocessing(
        file_path=input_file,
        out_dir=str(output_dir)
    )

    # Check that outputs are DataFrames
    assert isinstance(X_train, pd.DataFrame)
    assert isinstance(X_test, pd.DataFrame)

    # Train and test must contain the same features
    assert list(X_train.columns) == list(X_test.columns)

    # Check that the split happened correctly
    assert len(X_train) == 16
    assert len(X_test) == 4

    # Check that preprocessing removed missing values
    assert not X_train.isna().any().any()
    assert not X_test.isna().any().any()

    # Check for NaN/inf values
    assert np.isfinite(X_train.values).all()
    assert np.isfinite(X_test.values).all()

    # Check that transformers were saved
    assert (output_dir / "ohe.pkl").exists()
    assert (output_dir / "imputer.pkl").exists()
    assert (output_dir / "scaler.pkl").exists()