name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: guardian_qc_env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Run tests
        shell: bash -el {0}
        run: |
          pytest